select count(*) from Advise where A1='3'
select count(*) from Advise where A1='4'
select count(*) from Advise where A2='3'
select count(*) from Advise where A2='4'
select count(*) from Advise where A3='3'
select count(*) from Advise where A3='4'
select count(*) from Advise where A4='3'
select count(*) from Advise where A4='4'
select count(*) from Advise where A5='3'
select count(*) from Advise where A5='4'
select count(*) from Advise where A6='3'
select count(*) from Advise where A6='4'

--B
select count(*) from Advise where B1='3'
select count(*) from Advise where B1='4'
select count(*) from Advise where B2='3'
select count(*) from Advise where B2='4'
select count(*) from Advise where B3='3'
select count(*) from Advise where B3='4'
select count(*) from Advise where B4='3'
select count(*) from Advise where B4='4'
select count(*) from Advise where B5='3'
select count(*) from Advise where B5='4'
select count(*) from Advise where B6='3'
select count(*) from Advise where B6='4'
select count(*) from Advise where B7='3'
select count(*) from Advise where B7='4'

--C
select count(*) from Advise where C1='3'
select count(*) from Advise where C1='4'
select count(*) from Advise where C2='3'
select count(*) from Advise where C2='4'
select count(*) from Advise where C3='3'
select count(*) from Advise where C3='4'
select count(*) from Advise where C4='3'
select count(*) from Advise where C4='4'
select count(*) from Advise where C5='3'
select count(*) from Advise where C5='4'

--D
select count(*) from Advise where D1='3'
select count(*) from Advise where D1='4'
select count(*) from Advise where D2='3'
select count(*) from Advise where D2='4'
select count(*) from Advise where D3='3'
select count(*) from Advise where D3='4'
select count(*) from Advise where D4='3'
select count(*) from Advise where D4='4'
select count(*) from Advise where D5='3'
select count(*) from Advise where D5='4'
select count(*) from Advise where D6='3'
select count(*) from Advise where D6='4'
select count(*) from Advise where D7='3'
select count(*) from Advise where D7='4'
select count(*) from Advise where D8='3'
select count(*) from Advise where D8='4'
select count(*) from Advise where D9='3'
select count(*) from Advise where D9='4'
select count(*) from Advise where D10='3'
select count(*) from Advise where D10='4'

--E
select count(*) from Advise where E1='3'
select count(*) from Advise where E1='4'
select count(*) from Advise where E2='3'
select count(*) from Advise where E2='4'
select count(*) from Advise where E3='3'
select count(*) from Advise where E3='4'
select count(*) from Advise where E4='3'
select count(*) from Advise where E4='4'
--F
select count(*) from Advise where F1='3'
select count(*) from Advise where F1='4'
select count(*) from Advise where F2='3'
select count(*) from Advise where F2='4'
select count(*) from Advise where F3='3'
select count(*) from Advise where F3='4'
select count(*) from Advise where F4='3'
select count(*) from Advise where F4='4'

--G
select count(*) from Advise where G1='3'
select count(*) from Advise where G1='4'
select count(*) from Advise where G2='3'
select count(*) from Advise where G2='4'
select count(*) from Advise where G3='3'
select count(*) from Advise where G3='4'
select count(*) from Advise where G4='3'
select count(*) from Advise where G4='4'
select count(*) from Advise where G5='3'
select count(*) from Advise where G5='4'
select count(*) from Advise where G6='3'
select count(*) from Advise where G6='4'
select count(*) from Advise where G7='3'
select count(*) from Advise where G7='4'
select count(*) from Advise where G8='3'
select count(*) from Advise where G8='4'
select count(*) from Advise where G9='3'
select count(*) from Advise where G9='4'
select count(*) from Advise where G10='3'
select count(*) from Advise where G10='4'

--type
select count(*) from Advise where type='1'